services:
  pg_db:
    image: postgres:17
    container_name: pg_db_container
    environment:
      - POSTGRES_PASSWORD=saveliy
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - petition_service_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache_db:
    image: redis:7.4
    container_name: redis_container
    networks:
      - petition_service_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  petition_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petition_service_container
    environment:
      - DB_HOST={DB_HOST}
      - PORT={DB_PORT}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Используем переменную из окружения
      - PHOTOS_DIRECTORY=${PHOTOS_DIRECTORY}  # Используем переменную из окружения
      - REDIS_HOST={REDIS_HOST}
      - REDIS_PORT={REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Используем переменную и
    networks:
      - petition_service_net
    ports:
      - 8000:8000
    depends_on:
      pg_db:
        condition: service_healthy
      cache_db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - petition_service_net
    ports:
      - "9090:9090"

networks:
  petition_service_net:
    external: true



volumes:
  postgres_volume:
    name: postgres_volume
